### PR TITLE
Upgrade deps and peg versions

### PR DESCRIPTION
**Pull request by bjornharrtell**

### CODE REVIEW

**Comment by nathanboktae** [comment]
Pegging a peer depedency like phantomjs is a bad idea.

The whole point of semver is that you can move up in patch and minor versions without compatibility issues.

Are you seeing any particular issues?

**Comment by bjornharrtell** [comment]
No issues, just upgrade-mania I guess and a way to say "perhaps it's time to upgrade deps".

While I like the semver way of versioning and try to follow it myself, I do think updates still should be manually handled because you don't know for sure if a dependency has maintained compatibility regardless of intentions. Also using non-pegged versioning can result in non-identical builds from the same source which I also think can be a potential issue. But opinions vary and that's ok with me.

To conclude, feel free to ignore this PR. :)

**Comment by nathanboktae** [comment]
Pegging a peerDepedency version is a really bad idea. if someone globally installs this `mocha-phantomjs` and has 1.9.17 installed it will uninstall that version and go to 1.9.16. 

And in general, I disagree with you. the community is good at keeping to semver - we occasionally see issues, but we see them earlier rather than later this way.

**Comment by metaskills** [comment]
Agreed too Nathan. Thanks to you both too.

**Pull request closed without merging**
