### PR TITLE
Update phantom peerDependency to more lax.

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by nathanboktae** [comment]
Phantomjs minor versions have been pretty major... Not to mention 1.10 will likely never come as phantomjs 2 is the focus.

What's the motination for this?

**Comment by samccone** [comment]
Well this version was quite old and it was preprint npm installs (due to peerdep hell) from working ... So eh I kinda wanted to loosen the restriction and allow users to be explicit and choose and earlier version if they would like.

**Comment by metaskills** [comment]
Earlier than 1.9.1?

**Comment by nathanboktae** [comment]
Phantomjs 2 just came out - I doubt 1.10 will ever come out.

**Comment by samccone** [comment]
dope

**Pull request closed without merging**
